### PR TITLE
Header/Footer display on top of everything else

### PR DESCRIPTION
**Pull request by elp49**

### CODE REVIEW

**Review by mneedleman — APPROVED** [review]
This error is symptomatic of a larger issue, and adding a z-index is just a band-aid. But given the time constraint, this will have to do.

**Review by rao53 — APPROVED** [review]

**Comment by rao53** [comment]
> This error is symptomatic of a larger issue, and adding a z-index is just a band-aid. But given the time constraint, this will have to do.

What would be a good alternative?

**Comment by mneedleman** [comment]
> 
> 
> > This error is symptomatic of a larger issue, and adding a z-index is just a band-aid. But given the time constraint, this will have to do.
> 
> What would be a good alternative?

The issue lies with overlapping grids. Making them display on top just moves them out of the way, but the body of the app will still have issues

**Comment by elp49** [comment]
> > > This error is symptomatic of a larger issue, and adding a z-index is just a band-aid. But given the time constraint, this will have to do.
> > 
> > 
> > What would be a good alternative?
> 
> The issue lies with overlapping grids. Making them display on top just moves them out of the way, but the body of the app will still have issues

from what I've seen, this happens when `position:relative` and `position:fixed/absolute` clash

**Pull request merged**
